// Code generated by protoc-gen-go. DO NOT EDIT.
// source: leavemsg.proto

/*
Package types is a generated protocol buffer package.

It is generated from these files:
	leavemsg.proto

It has these top-level messages:
	SendMsgParam
	QueryMsgParam
	LeaveMsgAction
	SendLog
	QueryMsgResult
*/
package types

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SendMsgParam struct {
	Msg  string `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
	From string `protobuf:"bytes,2,opt,name=from" json:"from,omitempty"`
	To   string `protobuf:"bytes,3,opt,name=to" json:"to,omitempty"`
}

func (m *SendMsgParam) Reset()                    { *m = SendMsgParam{} }
func (m *SendMsgParam) String() string            { return proto.CompactTextString(m) }
func (*SendMsgParam) ProtoMessage()               {}
func (*SendMsgParam) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SendMsgParam) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *SendMsgParam) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *SendMsgParam) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

type QueryMsgParam struct {
	Addr string `protobuf:"bytes,1,opt,name=addr" json:"addr,omitempty"`
}

func (m *QueryMsgParam) Reset()                    { *m = QueryMsgParam{} }
func (m *QueryMsgParam) String() string            { return proto.CompactTextString(m) }
func (*QueryMsgParam) ProtoMessage()               {}
func (*QueryMsgParam) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *QueryMsgParam) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

type LeaveMsgAction struct {
	// Types that are valid to be assigned to Value:
	//	*LeaveMsgAction_Send
	//	*LeaveMsgAction_Query
	Value isLeaveMsgAction_Value `protobuf_oneof:"value"`
	Ty    int32                  `protobuf:"varint,3,opt,name=ty" json:"ty,omitempty"`
}

func (m *LeaveMsgAction) Reset()                    { *m = LeaveMsgAction{} }
func (m *LeaveMsgAction) String() string            { return proto.CompactTextString(m) }
func (*LeaveMsgAction) ProtoMessage()               {}
func (*LeaveMsgAction) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type isLeaveMsgAction_Value interface {
	isLeaveMsgAction_Value()
}

type LeaveMsgAction_Send struct {
	Send *SendMsgParam `protobuf:"bytes,1,opt,name=send,oneof"`
}
type LeaveMsgAction_Query struct {
	Query *QueryMsgParam `protobuf:"bytes,2,opt,name=query,oneof"`
}

func (*LeaveMsgAction_Send) isLeaveMsgAction_Value()  {}
func (*LeaveMsgAction_Query) isLeaveMsgAction_Value() {}

func (m *LeaveMsgAction) GetValue() isLeaveMsgAction_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *LeaveMsgAction) GetSend() *SendMsgParam {
	if x, ok := m.GetValue().(*LeaveMsgAction_Send); ok {
		return x.Send
	}
	return nil
}

func (m *LeaveMsgAction) GetQuery() *QueryMsgParam {
	if x, ok := m.GetValue().(*LeaveMsgAction_Query); ok {
		return x.Query
	}
	return nil
}

func (m *LeaveMsgAction) GetTy() int32 {
	if m != nil {
		return m.Ty
	}
	return 0
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*LeaveMsgAction) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _LeaveMsgAction_OneofMarshaler, _LeaveMsgAction_OneofUnmarshaler, _LeaveMsgAction_OneofSizer, []interface{}{
		(*LeaveMsgAction_Send)(nil),
		(*LeaveMsgAction_Query)(nil),
	}
}

func _LeaveMsgAction_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*LeaveMsgAction)
	// value
	switch x := m.Value.(type) {
	case *LeaveMsgAction_Send:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Send); err != nil {
			return err
		}
	case *LeaveMsgAction_Query:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Query); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("LeaveMsgAction.Value has unexpected type %T", x)
	}
	return nil
}

func _LeaveMsgAction_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*LeaveMsgAction)
	switch tag {
	case 1: // value.send
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SendMsgParam)
		err := b.DecodeMessage(msg)
		m.Value = &LeaveMsgAction_Send{msg}
		return true, err
	case 2: // value.query
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(QueryMsgParam)
		err := b.DecodeMessage(msg)
		m.Value = &LeaveMsgAction_Query{msg}
		return true, err
	default:
		return false, nil
	}
}

func _LeaveMsgAction_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*LeaveMsgAction)
	// value
	switch x := m.Value.(type) {
	case *LeaveMsgAction_Send:
		s := proto.Size(x.Send)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *LeaveMsgAction_Query:
		s := proto.Size(x.Query)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type SendLog struct {
	Msg  string `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
	Echo string `protobuf:"bytes,2,opt,name=echo" json:"echo,omitempty"`
	From string `protobuf:"bytes,3,opt,name=from" json:"from,omitempty"`
	To   string `protobuf:"bytes,4,opt,name=to" json:"to,omitempty"`
}

func (m *SendLog) Reset()                    { *m = SendLog{} }
func (m *SendLog) String() string            { return proto.CompactTextString(m) }
func (*SendLog) ProtoMessage()               {}
func (*SendLog) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *SendLog) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *SendLog) GetEcho() string {
	if m != nil {
		return m.Echo
	}
	return ""
}

func (m *SendLog) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *SendLog) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

type QueryMsgResult struct {
	Msg  string `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
	From string `protobuf:"bytes,2,opt,name=from" json:"from,omitempty"`
	To   string `protobuf:"bytes,3,opt,name=to" json:"to,omitempty"`
}

func (m *QueryMsgResult) Reset()                    { *m = QueryMsgResult{} }
func (m *QueryMsgResult) String() string            { return proto.CompactTextString(m) }
func (*QueryMsgResult) ProtoMessage()               {}
func (*QueryMsgResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *QueryMsgResult) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *QueryMsgResult) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *QueryMsgResult) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func init() {
	proto.RegisterType((*SendMsgParam)(nil), "types.sendMsgParam")
	proto.RegisterType((*QueryMsgParam)(nil), "types.queryMsgParam")
	proto.RegisterType((*LeaveMsgAction)(nil), "types.LeaveMsgAction")
	proto.RegisterType((*SendLog)(nil), "types.SendLog")
	proto.RegisterType((*QueryMsgResult)(nil), "types.queryMsgResult")
}

func init() { proto.RegisterFile("leavemsg.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 252 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0x9b, 0x7f, 0x16, 0xa7, 0x1a, 0x64, 0xf4, 0x90, 0xa3, 0xc4, 0x8b, 0x82, 0xe4, 0x50,
	0x9f, 0x40, 0x11, 0xe9, 0xa1, 0x05, 0xd9, 0x3e, 0xc1, 0xda, 0x8c, 0xab, 0x90, 0x64, 0xea, 0xee,
	0xa6, 0x90, 0xab, 0x4f, 0x2e, 0x19, 0x9b, 0xa0, 0xe8, 0xa9, 0xb7, 0x8f, 0xe1, 0x63, 0xe6, 0xf7,
	0xdb, 0x85, 0xb4, 0x22, 0xbd, 0xa3, 0xda, 0x99, 0x62, 0x6b, 0xd9, 0x33, 0x26, 0xbe, 0xdb, 0x92,
	0xcb, 0x1f, 0xe1, 0xc4, 0x51, 0x53, 0xae, 0x9c, 0x79, 0xd6, 0x56, 0xd7, 0x78, 0x06, 0x51, 0xed,
	0x4c, 0x16, 0x5c, 0x06, 0xd7, 0xc7, 0xaa, 0x8f, 0x88, 0x10, 0xbf, 0x5a, 0xae, 0xb3, 0x50, 0x46,
	0x92, 0x31, 0x85, 0xd0, 0x73, 0x16, 0xc9, 0x24, 0xf4, 0x9c, 0x5f, 0xc1, 0xe9, 0x47, 0x4b, 0xb6,
	0x1b, 0xd7, 0x20, 0xc4, 0xba, 0x2c, 0xed, 0x7e, 0x8f, 0xe4, 0xfc, 0x33, 0x80, 0x74, 0xd9, 0x43,
	0xac, 0x9c, 0xb9, 0xdf, 0xf8, 0x77, 0x6e, 0xf0, 0x06, 0xe2, 0xfe, 0xba, 0xd4, 0x66, 0xf3, 0xf3,
	0x42, 0x98, 0x8a, 0x9f, 0x40, 0x8b, 0x89, 0x92, 0x0a, 0xde, 0x42, 0x22, 0x27, 0x84, 0x63, 0x36,
	0xbf, 0xd8, 0x77, 0x7f, 0x9d, 0x5d, 0x4c, 0xd4, 0x77, 0x49, 0x00, 0x3b, 0x01, 0x4c, 0x54, 0xe8,
	0xbb, 0x87, 0x29, 0x24, 0x3b, 0x5d, 0xb5, 0x94, 0xaf, 0x61, 0xba, 0xa6, 0xa6, 0x5c, 0xb2, 0xf9,
	0x5f, 0x95, 0x36, 0x6f, 0x3c, 0xa8, 0xf6, 0x79, 0xd4, 0x8f, 0xfe, 0xe8, 0xc7, 0xa3, 0xfe, 0x13,
	0xa4, 0x03, 0x87, 0x22, 0xd7, 0x56, 0xfe, 0xb0, 0x67, 0x7c, 0x39, 0x92, 0xaf, 0xb9, 0xfb, 0x0a,
	0x00, 0x00, 0xff, 0xff, 0xa7, 0x49, 0xc0, 0xdc, 0xac, 0x01, 0x00, 0x00,
}
